### ISSUE TITLE
Why not using latest pandas and numpy

### ISSUE THREAD

**Issue by TRANTANKHOA** [awslabs/aws-data-wrangler#817]
Hi everyone,

I'm having a dependency conflict while integrating awswrangler to our repos due to 
```
numpy>=1.18.0,<1.21.0
pandas>=1.1.0,<1.3.0
```
as of ver. 2.9.0 since we have a renovate-bot which automatically bump these version to the latest available. So my questions

1. Why limit the version to exclude the latest?
2. How should people avoid this issue? 
 
We have a large number of repos and all of them have latest version for pandas, numpy so if I fix one of them I have to fix all of them to keep them compatible.

**Comment by jaidisido** [comment]
Hi @TRANTANKHOA, pandas [1.3.0](https://pypi.org/project/pandas/) and numpy [1.21.0](https://pypi.org/project/numpy/) are already the latest versions of the libraries. Are you trying to install pre-release dev versions by any chance?

As to why we fix the versions, please refer to this [issue](https://github.com/awslabs/aws-data-wrangler/issues/805).

**Comment by TRANTANKHOA** [comment]
Thanks @jaidisido , please note that the spec from awswrangler excludes pandas 1.3.0 and numpy 1.21.0 with `<` operator while our bot would specify that pandas==1.3.0 and numpy==1.21.0 hence the conflict.

**Comment by jaidisido** [comment]
Ah my bad, I was looking at the current [requirements.txt](https://github.com/awslabs/aws-data-wrangler/blob/main/requirements.txt) file which will be effective in the next release (2.10.0) scheduled for next week.

**Comment by jaidisido** [comment]
Fixed in 2.10.0 release

**Comment by TRANTANKHOA** [comment]
The main issue is pandas version < latest version as a requirement. so the same issue is for 2.10 still. Can we remove that?

**Comment by shuwenz1218** [comment]
![23F69B97-17EB-49D2-A5C6-388BEB09A905_4_5005_c](https://user-images.githubusercontent.com/86645145/129533315-8dda7a00-3882-4dd7-882f-dfca5bf868d9.jpeg)
I can not install the awswrangler package on Glue as well, and I believe the root cause is related with this issue.
I am still seeing the bug is not being fixed on release 2.10.0, could we have an outlook date on next release.
@jaidisido Thank you
